# Generated by Django 2.2.7 on 2019-12-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classification',
            field=models.CharField(choices=[('Buy', 'Buyer'), ('Sell', 'Seller')], max_length=10),
        ),
    ]
