# Generated by Django 2.1.7 on 2019-12-04 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191204_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cart',
            field=models.ManyToManyField(related_name='cartin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='wish',
            field=models.ManyToManyField(related_name='wishin', to=settings.AUTH_USER_MODEL),
        ),
    ]
