# Generated by Django 2.1.7 on 2019-12-05 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20191204_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='cart',
            field=models.ManyToManyField(related_name='cart_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'auction'), (2, 'purchased in progress'), (3, 'purchased completed')], default=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='wish',
            field=models.ManyToManyField(related_name='wish_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
