# Generated by Django 2.1.7 on 2019-12-05 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0006_auto_20191205_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionhistory',
            options={'ordering': ['-price']},
        ),
        migrations.AddField(
            model_name='auctionhistory',
            name='bidder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auction_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionhistory',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auctionhistory',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auction_history', to='product.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
