# Generated by Django 2.2.8 on 2019-12-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20191207_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='trading_place',
            field=models.CharField(max_length=100),
        ),
    ]
