# Generated by Django 2.2.7 on 2019-12-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20191209_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='img/no_image.png', upload_to='img/'),
        ),
    ]
