# Generated by Django 2.1.7 on 2019-12-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20191209_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
