# Generated by Django 2.2.7 on 2019-12-03 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cell',
            new_name='Sell',
        ),
    ]
